import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.scss";

import Header from "../components/header/header";
import BlockImg from "../components/BlockImg/BlockImg";
import BlockPresentation from "../components/blockPresentation/blockPresentation";
import BlockImgyFrase from "../components/blockImgyFrase/blockImgyFrase";
import Blockquienessomos from "../components/Blockquienessomos/blockquienessomos";
import BlockNuestrosServicios from "../components/BlockNuestrosServicios/blocknuestrosservicios";
import BlockPortfolio from "../components/BlockPortfolio/blockportfolio";
import BlockImgCierre from "../components/BlockImgCierre/blockimgcierre";


export default function Home() {
  return (
    <>
      <Head>
        <title>Estudio Valiente</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.topline}>
        <Image 
              src="/images/barra-encabezado.png"
              alt="Linea decorativa"
              width={414}
              height={50}
              layout="responsive"
              className={styles.image}
            />
        </div>
      <div className={styles.container}>
        <Header />
        <BlockImg />
        <BlockPresentation />
        <BlockImgyFrase />
        <Blockquienessomos />
        <BlockNuestrosServicios />
        <BlockPortfolio />
        <BlockImgCierre />
      </div>
    </>
  );
}
